### ISSUE TITLE
Publish package on NPM

### ISSUE THREAD

**Issue by RomainSauvaire** [Pixabay/JavaScript-flexImages#1]
Hello there,

Thank you for this nice piece of code.

Since a lot of developers use NPM rather than Bower, it would be great to publish it on NPM. Would it be feasible for you ?

Best regards

**Comment by SimonSteinberger** [comment]
If you like, please publish it on your own. You have permission to do so. Not using NPM myself, I'm don't have the experience, yet - and not enough time to dog into it.

**Comment by herrbischoff** [comment]
I just went ahead and published it: https://www.npmjs.com/package/javascript-flex-images
